// Seed weather data for Hazel Green, AL area (MVP)

export const WEATHER_SEED = [
  {
    date: '2026-05-21',
    label: 'Today',
    high: 82,
    low: 61,
    condition: 'Partly Cloudy',
    precip: 10,
    windMph: 8,
    humidity: 65,
    dispatchRisk: 'low',
    riskReason: 'Normal conditions',
  },
  {
    date: '2026-05-22',
    label: 'Tomorrow',
    high: 79,
    low: 60,
    condition: 'Scattered Showers',
    precip: 60,
    windMph: 12,
    humidity: 78,
    dispatchRisk: 'medium',
    riskReason: 'Rain may slow pour schedules — check with foremen',
  },
  {
    date: '2026-05-23',
    label: 'Friday',
    high: 75,
    low: 58,
    condition: 'Thunderstorms',
    precip: 85,
    windMph: 18,
    humidity: 88,
    dispatchRisk: 'high',
    riskReason: 'Thunderstorms expected — possible dispatch hold, monitor AM',
  },
  {
    date: '2026-05-24',
    label: 'Saturday',
    high: 80,
    low: 62,
    condition: 'Mostly Clear',
    precip: 15,
    windMph: 6,
    humidity: 60,
    dispatchRisk: 'low',
    riskReason: 'Clear up — good pour conditions',
  },
  {
    date: '2026-05-25',
    label: 'Sunday',
    high: 85,
    low: 65,
    condition: 'Sunny',
    precip: 5,
    windMph: 5,
    humidity: 55,
    dispatchRisk: 'low',
    riskReason: 'Excellent conditions',
  },
]

export const RISK_COLORS = {
  low: '#5BA66E',
  medium: '#D4A03C',
  high: '#D45555',
}
